### ISSUE TITLE
FAB does not dock properly 

### ISSUE THREAD

**Issue by humble-git** [marianocordoba/fab-circular-menu#19]
When I tried to dock the FAB menu using central dock, it does not follow the proper alignment 

![image](https://user-images.githubusercontent.com/67156984/91270901-ff25cf00-e796-11ea-9a6f-58dd8e34cff7.png)

**Comment by marianocordoba** [comment]
Hi! This widget isn't mean to be docked. You can align it to the top center of your bottom bar, but it will not dock.

![Example](https://i.imgur.com/GKDxSUd.png "Example")

**Comment by harlanx** [comment]
I have tried to align it in bottom center by Alignment(-0.1, 1.0)  and FractionalOffset(0.45, 1.0) because Alignment.bottomCenter is positioned a little bit to the right.
The problem is when showing the children because it does not behave like when using Alignment.bottomCenter.

My current workaround is using Positioned.fill with property left: -32.
